### ISSUE TITLE
Feedback on Network configuration - NFS

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-apps-dbs#16]
### Summary

Regarding description of VMware vSphere with ONTAP this page, let me confirm it as follows.

The first section of this page says:
Don't connect hosts directly to storage; use switches to have redundant paths and allow VMware HA to work without intervention.

Question:
Please let me know why do not connect directly from the host in a VMware vSphere environment.
I understand that the ONTAP supports iSCSI direct connections from host.

[https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-ha-pairs-reference.html](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fontap%2Fsan-config%2Fconfigure-iscsi-san-hosts-ha-pairs-reference.html&data=05%7C02%7CChanda.Jha%40netapp.com%7C102ab3c3b04144eb15e208dc278269e6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638428688293186271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=B7naYVSv7uRuzp2ynoepuE41N0pd4eVMTviXsREHtPo%3D&reserved=0)
[https://community.netapp.com/t5/ONTAP-Discussions/Netapp-iSCSi-direct-attach/m-p/156512](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.netapp.com%2Ft5%2FONTAP-Discussions%2FNetapp-iSCSi-direct-attach%2Fm-p%2F156512&data=05%7C02%7CChanda.Jha%40netapp.com%7C102ab3c3b04144eb15e208dc278269e6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638428688293206069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2qzsU9yON%2FOzz1hAj%2FCoZr4wSQCCd%2BDB4mcCAwdvofY%3D&reserved=0)

Best Regards,
Shinichi Kondo

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
This is part of the best practice guide. It is the best practice to use a switch with iSCSI. All other protocols require it.

For example, with NFS, the LIF will migrate from one node to another during failover.

For Fibre Channel based protocols it is required because ONTAP uses NPIV for FC LIFs. A switch is required to support NPIV.

With iSCSI you can use a switch, but you really do want to take care and ensure failover works as expected and make sure you have a path to both nodes in an HA pair.

By using a switch, you can scale out and add more hosts and provide for greater failure tolerance and load balancing in an ESXi host cluster.

**Comment by netapp-ehoffman** [comment]
@netapp-chandaj , has this update been communicated to the submitter of the original doccomment?

**Comment by jfsinmsp** [comment]
Yes, Chance provided an update.

**Comment by jfsinmsp** [comment]
Created an _include section that covers this topic and added it to both the VMware and Oracle sections. It's generic information and could be used by other apps if needed. Pushing to public shortly and will email the original account team.
